loggerLevel: info
alerter:
  fromEmail: chronica-alerts@my.com
  admins:
  - email: me@my.com
tracker:
  debounceCount: 2
reporter:
  helloDelay: 16000 # send an email 16 seconds after starting
  dailyEnabled: true
  hour: 16 # 16:10 (pm)
  minute: 10
urlMonitor:
  period: 45000 # check every 45 seconds
  timeout: 8000 # connection timeout after 8 seconds
  services:
  - url: http://google.com
    label: Google Inc # default name and label taken from URL
  - url: http://facebook.com
    name: fb # default name and label taken from URL
