loggerLevel: info
alerter:
  fromEmail: chronica-alerts@my.com
  admins:
  - email: me@my.com
tracker: # tracks the status and decides if and when the send an email alert
  debounceCount: 2 # status must stay changed during multiple iterations before alert
reporter:
  helloDelay: 16000 # send an email 16 seconds after starting
  dailyEnabled: true
  hour: 16 # 16:10 (pm)
  minute: 10
urlMonitor:
  period: 25000 # check status every 45 seconds
  timeout: 8000 # HTTP connection timeout after 8 seconds
  services:
  - url: http://google.com
    label: Google Inc # default name and label taken from URL
  - url: http://facebook.com
    name: fb # default name and label taken from URL
